# Generated by Django 2.1.4 on 2019-05-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liquid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contents', models.TextField()),
                ('image', models.ImageField(default='default_liquid.jpg', upload_to='liquid_pics')),
            ],
        ),
    ]
